run-all:
	python3 src/aggregate_dti_fred.py
	python3 src/yield_curve_dashboard.py
	python3 src/real_rates_dashboard.py

run-household:
	python3 src/household_dti_dashboard.py

run-all-plus-household:
	python3 src/aggregate_dti_fred.py
	python3 src/yield_curve_dashboard.py
	python3 src/real_rates_dashboard.py
	python3 src/household_dti_dashboard.py
